/**
 * @fileoverview Unit tests for POC Service
 * Uses Node.js built-in test runner (node:test)
 */

import { test, describe, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert';
import path from 'node:path';
import fs from 'fs-extra';
import os from 'node:os';

import { FileStorageProvider } from '../../src/epic/providers/file-storage-provider.js';
import { EpicService } from '../../src/epic/services/epic-service.js';
import { StoryService } from '../../src/epic/services/story-service.js';
import { StoryIndexService } from '../../src/epic/services/story-index-service.js';
import { POCService } from '../../src/epic/services/poc-service.js';
import { AIProvider, AI_PROVIDER_TYPE } from '../../src/epic/providers/ai-provider.js';
import { NotFoundError } from '../../src/epic/utils/errors.js';

// Test directory setup
let testRoot;
let storage;
let epicService;
let storyService;
let storyIndexService;
let aiProvider;
let pocService;

// Mock AI provider that returns predictable content
function createMockAIProvider() {
  return new AIProvider({
    provider: AI_PROVIDER_TYPE.LOCAL,
  });
}

beforeEach(async () => {
  testRoot = path.join(os.tmpdir(), `poc-service-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  await fs.ensureDir(testRoot);
  storage = new FileStorageProvider(testRoot);
  storyIndexService = new StoryIndexService(storage);
  epicService = new EpicService(storage, storyIndexService);
  storyService = new StoryService(storage, storyIndexService, epicService);
  aiProvider = createMockAIProvider();
  pocService = new POCService(storage, storyService, aiProvider);
  await storage.ensureDirectories();
});

afterEach(async () => {
  if (testRoot) {
    await fs.remove(testRoot);
  }
});

describe('POCService', () => {
  describe('generate', () => {
    test('generates POC for a story', async () => {
      const epic = await epicService.create({ name: 'Test Epic' });
      const story = await storyService.create(epic.id, {
        title: 'Login Feature',
        type: 'feature',
        description: 'User login functionality',
      });

      const result = await pocService.generate(story.id);

      assert.ok(result.poc);
      assert.ok(result.poc.includes('[LOCAL AI RESPONSE]'));
      assert.strictEqual(result.story.id, story.id);
      assert.ok(result.metadata.generatedAt);
      assert.strictEqual(result.metadata.storyId, story.id);
    });

    test('includes step content in specification', async () => {
      const epic = await epicService.create({ name: 'Test Epic' });
      const story = await storyService.create(epic.id, {
        title: 'Test Feature',
        type: 'feature',
      });

      // Complete init step
      await storyService.updateStep(story.id, 'init', {
        completed: true,
        content: 'This is the feature init content',
      });

      const result = await pocService.generate(story.id);

      assert.ok(result.poc);
      assert.ok(result.metadata);
    });

    test('throws NotFoundError for non-existent story', async () => {
      await assert.rejects(
        async () => {
          await pocService.generate('non-existent');
        },
        NotFoundError
      );
    });

    test('accepts additional context', async () => {
      const epic = await epicService.create({ name: 'Test Epic' });
      const story = await storyService.create(epic.id, {
        title: 'Test Feature',
        type: 'feature',
      });

      const result = await pocService.generate(story.id, {
        context: 'Using React and TypeScript',
      });

      assert.ok(result.poc);
    });
  });

  describe('generateAndSave', () => {
    test('generates and saves POC to attachment', async () => {
      const epic = await epicService.create({ name: 'Test Epic' });
      const story = await storyService.create(epic.id, {
        title: 'Test Feature',
        type: 'feature',
      });

      const result = await pocService.generateAndSave(story.id, 'poc.js');

      assert.ok(result.poc);
      assert.strictEqual(result.savedAs, 'poc.js');
      assert.ok(result.poc.includes('POC Generated by AIA Code'));

      // Verify attachment was added to story
      const updatedStory = await storyService.getById(story.id);
      assert.ok(updatedStory.attachments.includes('poc.js'));
    });

    test('can read saved POC', async () => {
      const epic = await epicService.create({ name: 'Test Epic' });
      const story = await storyService.create(epic.id, {
        title: 'Test Feature',
        type: 'feature',
      });

      await pocService.generateAndSave(story.id, 'poc.js');
      const poc = await pocService.getPOC(story.id, 'poc.js');

      assert.ok(poc.includes('POC Generated by AIA Code'));
    });
  });

  describe('listPOCs', () => {
    test('lists code file attachments', async () => {
      const epic = await epicService.create({ name: 'Test Epic' });
      const story = await storyService.create(epic.id, {
        title: 'Test Feature',
        type: 'feature',
      });

      // Save multiple POCs
      await pocService.generateAndSave(story.id, 'poc1.js');
      await pocService.generateAndSave(story.id, 'poc2.ts');

      const pocs = await pocService.listPOCs(story.id);

      assert.strictEqual(pocs.length, 2);
      assert.ok(pocs.includes('poc1.js'));
      assert.ok(pocs.includes('poc2.ts'));
    });

    test('filters non-code attachments', async () => {
      const epic = await epicService.create({ name: 'Test Epic' });
      const story = await storyService.create(epic.id, {
        title: 'Test Feature',
        type: 'feature',
      });

      // Save POC and non-code file
      await pocService.generateAndSave(story.id, 'poc.js');
      await storage.saveAttachment(story.id, 'notes.txt', Buffer.from('notes'));

      // Update story attachments
      const { epic: freshEpic, story: freshStory } = await storyService.findStoryWithEpic(story.id);
      freshStory.attachments.push('notes.txt');
      await storage.writeEpic(freshEpic);

      const pocs = await pocService.listPOCs(story.id);

      assert.strictEqual(pocs.length, 1);
      assert.ok(pocs.includes('poc.js'));
    });
  });

  describe('deletePOC', () => {
    test('deletes POC and removes from attachments', async () => {
      const epic = await epicService.create({ name: 'Test Epic' });
      const story = await storyService.create(epic.id, {
        title: 'Test Feature',
        type: 'feature',
      });

      await pocService.generateAndSave(story.id, 'poc.js');
      await pocService.deletePOC(story.id, 'poc.js');

      const updatedStory = await storyService.getById(story.id);
      assert.ok(!updatedStory.attachments.includes('poc.js'));

      const pocs = await pocService.listPOCs(story.id);
      assert.strictEqual(pocs.length, 0);
    });
  });

  describe('checkReadiness', () => {
    test('returns ready when init is completed', async () => {
      const epic = await epicService.create({ name: 'Test Epic' });
      const story = await storyService.create(epic.id, {
        title: 'Test Feature',
        type: 'feature',
      });

      await storyService.updateStep(story.id, 'init', { completed: true, content: 'Init' });
      await storyService.updateStep(story.id, 'specFunc', { skipped: true });

      const result = await pocService.checkReadiness(story.id);

      assert.strictEqual(result.ready, true);
    });

    test('returns not ready when init is not completed', async () => {
      const epic = await epicService.create({ name: 'Test Epic' });
      const story = await storyService.create(epic.id, {
        title: 'Test Feature',
        type: 'feature',
      });

      const result = await pocService.checkReadiness(story.id);

      assert.strictEqual(result.ready, false);
      assert.ok(result.issues.some((i) => i.includes('Init')));
    });
  });

  describe('regenerate', () => {
    test('regenerates POC with modifications', async () => {
      const epic = await epicService.create({ name: 'Test Epic' });
      const story = await storyService.create(epic.id, {
        title: 'Test Feature',
        type: 'feature',
      });

      const existingPoc = 'function login() { return true; }';
      const modifications = 'Add error handling';

      const result = await pocService.regenerate(story.id, existingPoc, modifications);

      assert.ok(result);
      assert.ok(result.includes('[LOCAL AI RESPONSE]'));
    });
  });
});
